### ISSUE TITLE
Global: Use of Concentration mod

### ISSUE THREAD

**Issue by contrarybaton60** [ViolaFlower/Re-Console-Legacy#1]
if you know you know.

duplicate of https://github.com/ViolaFlower/Re-Console/issues/149
![Screenshot from 2024-12-24 20-37-47](https://github.com/user-attachments/assets/dfcd9fe2-1521-478b-98b5-2df832dbd011)

**Comment by omo50** [comment]
this is required for hotjoin as of now, but will see abt 0.0.11 for a fix (early january)

**Comment by contrarybaton60** [comment]
you should make a list of known bugs so duplicates shouldn't happen
