### ISSUE TITLE
Global: failed to load tutorial world

### ISSUE THREAD

**Issue by contrarybaton60** [ViolaFlower/Re-Console-Legacy#7]
![2024-12-24_21 16 24](https://github.com/user-attachments/assets/276bbbde-8144-4429-9fd2-aeb0535cbfae)

**Comment by contrarybaton60** [comment]
![2024-12-24_21 20 27](https://github.com/user-attachments/assets/b26f7c20-51e7-4411-b173-3e9a2fb8a888)
![2024-12-24_21 18 17](https://github.com/user-attachments/assets/99a88368-06ae-4256-8fd0-59ba4fa62fc4)
affects globally

**Comment by omo50** [comment]
fixed in RC-L-Resources [``862e620``](https://github.com/ViolaFlower/RC-L-Resources/commit/862e620393f717262c9aa43fa46d9ca24c9a6c42)
